services:
  frontend-finance-accounts-payble:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3134:80'
    networks:
      - financial-accounts-payable-network

networks:
  financial-accounts-payable-network:
    name: financial-accounts-payable-network
