services:
  frontend-finance-accounts-payble:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3134:80'
    networks:
      - finance-accounts-payble-network

networks:
  financial-accounts-payble-network:
    name: financial-accounts-payble-network
