services:
  api-financial-accounts-payable:
    build: .
    container_name: api-financial-accounts-payable
    restart: always
    ports:
      - 3135:3135
    env_file:
      - .env
    depends_on:
      - postgresql-financial-accounts-payable
    networks:
      - financial-accounts-payable-network
    volumes:
      - api_financial_accounts_payable_uploads:/usr/src/app/uploads

  postgresql-financial-accounts-payable:
    image: postgres:16
    ports:
      - 5438:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=financial-accounts-payable

    networks:
      - financial-accounts-payable-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  api_financial_accounts_payable_uploads:
networks:
  financial-accounts-payble-network:
    name: financial-accounts-payble-network
